version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.12"

python:
  install:
      # Install our python package before building the docs
    - method: pip
      path: .
      extra_requirements:
        - all
        - doc

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true
