[project]
name = "vfbLib"
version = "0.12.2"
description = "Tools for converting FontLab Studio 5 (VFB) files."
keywords = ["fonttools", "vfb", "vfbLib"]

readme = "README.md"
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]

authors = [{ name = "Jens Kutílek", email = "webmail@kutilek.de" }]
classifiers = [
  "Environment :: Console",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: 3.15",
]

requires-python = ">=3.11"
dependencies = [
  "fonttools[ufo] >= 4.66.1",
  "orjson >= 3.12.0, < 4",
  "typing_extensions >= 4.16.0",
  "ufoLib2[json] >= 0.18.1",
  "ufonormalizer >= 0.6.3",
]

[project.urls]
"Bug Tracker" = "https://github.com/LucasFonts/vfbLib/issues"
"Changelog" = "https://github.com/LucasFonts/vfbLib/blob/main/CHANGELOG.md"
"Documentation" = "https://vfblib.readthedocs.io/en/latest/"
"Homepage" = "https://github.com/LucasFonts/vfbLib"

[project.scripts]
vfb2json = "vfbLib.cmdline:vfb2json"
vfb2tth = "vfbLib.tth:vfb2tth"
vfb3ufo = "vfbLib.cmdline:vfb2ufo"
vfbcu2qu = "vfbLib.cu2qu:vfbcu2qu"
vfbdiff = "vfbLib.diff:diffvfb"
yuri = "vfbLib.value:yuri"

[project.optional-dependencies]
all = [
  "vfbLib[toml]",
  "vfbLib[yaml]",
]
doc = [
  "sphinx >= 9.0.0",  # Update to 9.1.0 when we drop Python 3.11
  "sphinx_rtd_theme >= 3.1.0",
]
toml = ["tomli-w >= 1.2.0"]
yaml = ["pyyaml >= 6.0.3"]

[dependency-groups]
dev = [
  "mypy >= 2.4.0",
  "ruff >= 0.16.10",
  "types-pyyaml >= 6.0.12.20260906",
]
test = [
  "pytest-cov >= 7.1.0",
  "pytest >= 9.1.1",
  "tox-gh >= 1.8.0",
  "tox-uv >= 1.36.1",
  "tox >= 4.64.9",
  { include-group = "dev" },
]

[build-system]
requires = ["uv_build>=0.12.23,<0.13"]
build-backend = "uv_build"

[tool.coverage.paths]
source = ["src", ".tox/py*/**/site-packages"]

[tool.ruff]
extend-exclude = ["Scripts"]

[tool.ruff.lint]
ignore = [
  "N999",  # Mixed case module names
  # "RUF023",  # Unsorted __slots__
]

[tool.ruff.lint.isort]
known-first-party = ["vfbLib"]

[tool.uv.build-backend]
module-name = "vfbLib"
# module-root = "src"
