[tox]
envlist =
    lint
    py31{1-4}
    ; mypy
    htmlcov
skip_missing_interpreters = true

[tool:pytest]
testpaths =
    Tests
addopts = 
    --cov-report=term-missing

[gh]
python =
    3.11 = py311
    3.12 = py312
    3.13 = py313
    3.14 = py314, htmlcov # , mypy

[testenv]
runner = uv-venv-lock-runner
dependency_groups =
    test
extras =
    toml
    yaml
commands =
    coverage run --parallel-mode -m pytest --ignore=Tests/Data --ignore=Scripts {posargs}

[testenv:mypy]
runner = uv-venv-lock-runner
setenv =
    MYPYPATH = {toxinidir}/Stubs
commands =
    mypy {posargs:src}

[testenv:lint]
description: Check import order and code formatting
runner = uv-venv-lock-runner
skip_install = true
commands =
    ruff check --select I  # Check import order
    ruff format --check --diff  # Check formatting
    flake8 src

[testenv:htmlcov]
description: Report coverage over all test runs
skip_install = true
commands =
    coverage combine
    coverage report
    coverage html

[testenv:clean]
skip_install = true
commands =
    coverage erase
